import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { GlobalStoreProvider } from "@/providers/globalStateProvider";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/providers/themeProvider";
import { DrawerCSSProvider } from "@/providers/drawerCSSProvider";
import { SettingStoreProvider } from "@/providers/settingStoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FiPi",
  description: "Generated by Elvin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DrawerCSSProvider>
            <GlobalStoreProvider>
              <SettingStoreProvider>{children}</SettingStoreProvider>
            </GlobalStoreProvider>
          </DrawerCSSProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
